version: '3.7'

services:
  postgres:
    container_name: db
    image: postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: fab-fetch
      POSTGRES_PORT: 5432
    ports:
      - '5432:5432'

  bot:
    container_name: fab-fetch
    build: .
    command: ["bash", "start.sh"]
    restart: unless-stopped
    depends_on:
      - postgres
    volumes:
      - ./data:/app/data:z

networks:
  default:
    driver: bridge