version: '3.7'

services:
  postgres:
    container_name: db
    image: postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: fab-fetch
      POSTGRES_PORT: 5432
    ports:
      - '5432:5432'

  bot-migrate:
    container_name: fab-fetch-migrate
    build: ..
    command: npx prisma migrate deploy && npm run migrate
    restart: 'no'
    depends_on:
      - postgres
    tty: true

networks:
  default:
    driver: bridge